#!/usr/bin/env bash
export TWITTER_CONSUMER_KEY=XXXX
export TWITTER_CONSUMER_SECRET=XXXX
export TWITTER_ACCESS_TOKEN=XXXX
export TWITTER_ACCESS_SECRET=XXXX

export BROKER=127.0.0.1:9092
export TOPIC=twitter_tweets
export GROUP_ID=my-fifth-app
export REPLICATION_FACTOR=1
export PARTITIONS=6

export ES_URL=XXXX
export ES_ACCESS_KEY=XXXX
export ES_ACCESS_SECRET=XXXX
